import React, { useMemo, useState } from 'react';
import { assessments as seedAssessments, controls as seedControls, documents as seedDocs, organization, questions, reports as seedReports, riskCategories, risks as seedRisks } from './data/seed';
import { assessmentLevelFromOverall, calcRiskScore, overallAssessmentScore, riskLevelFromScore } from './lib/scoring';
const nav=['Dashboard','Assessments','Risk Register','Controls','Documents','AI Assistant','Reports','Settings'];
export function App(){
  const [page,setPage]=useState('Dashboard'); const [risks,setRisks]=useState(seedRisks); const [docs,setDocs]=useState(seedDocs); const [assessments,setAssessments]=useState(seedAssessments); const [reports,setReports]=useState(seedReports); const [language,setLanguage]=useState('en'); const [ai,setAi]=useState('');
  const overall=useMemo(()=>overallAssessmentScore(risks),[risks]); const overallLevel=assessmentLevelFromOverall(overall);
  const dashboard=<div className='grid'>{card('Overall Risk Score',`${overall}/100`)}{card('Risk Level',overallLevel)}{card('Critical Risks',risks.filter(r=>r.level==='Critical').length)}{card('High Risks',risks.filter(r=>r.level==='High').length)}{card('Open Risks',risks.filter(r=>r.status==='Open').length)}</div>;
  const runAI=async(action,payload={})=>{const r=await fetch('http://localhost:4000/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload:{...payload,overallLevel},language})});const j=await r.json();setAi(j.result)};
  return <div className='app'><aside>{nav.map(n=><button key={n} onClick={()=>setPage(n)}>{n}</button>)}</aside><main><h1>RiskPilot AI</h1><p className='disc'>This tool supports risk assessment and reporting. It does not replace legal, regulatory, audit, or professional risk advice.</p>{page==='Dashboard'&&<>{dashboard}<button onClick={()=>runAI('summary')}>Generate AI Risk Posture Summary</button><pre>{ai}</pre></>}
  {page==='Assessments'&&<div><button onClick={()=>setAssessments(a=>[{id:`asm-${a.length+1}`,title:'New Assessment',scope:'Custom',status:'Draft',createdAt:new Date().toISOString(),organizationId:'org-1',completedAt:null,overallScore:0,riskLevel:'Low'},...a])}>Start New Assessment</button><table><tbody>{assessments.map(a=><tr key={a.id}><td>{a.title}</td><td>{a.scope}</td><td>{a.status}</td><td>{a.overallScore}</td><td>{a.riskLevel}</td></tr>)}</tbody></table><p>5-step workflow: scope → context → questionnaire ({questions.length} questions) → review risks → complete.</p></div>}
  {page==='Risk Register'&&<div><button onClick={()=>{const likelihood=3,impact=3,score=calcRiskScore(likelihood,impact);setRisks(r=>[{id:`risk-${r.length+1}`,assessmentId:'asm-2',title:'New risk',category:riskCategories[0],description:'Manual risk.',likelihood,impact,score,level:riskLevelFromScore(score),owner:'Risk Manager',status:'Open',recommendation:'Define remediation.',dueDate:'2026-08-01',createdAt:new Date().toISOString()},...r])}}>Add Risk</button><table><tbody>{risks.map(r=><tr key={r.id}><td>{r.title}</td><td>{r.category}</td><td>{r.likelihood}</td><td>{r.impact}</td><td>{r.score}</td><td>{r.level}</td><td>{r.owner}</td><td>{r.status}</td></tr>)}</tbody></table></div>}
  {page==='Controls'&&<table><tbody>{seedControls.map(c=><tr key={c.id}><td>{c.title}</td><td>{c.status}</td><td>{c.effectiveness}</td><td>{c.owner}</td></tr>)}</tbody></table>}
  {page==='Documents'&&<Documents docs={docs} setDocs={setDocs} runAI={runAI} ai={ai} />}
  {page==='AI Assistant'&&<div><button onClick={()=>runAI('findings')}>Analyze current assessment</button><button onClick={()=>runAI('plan')}>Create 30/60/90 day plan</button><button onClick={()=>runAI('summary')}>Draft executive summary</button><pre>{ai}</pre></div>}
  {page==='Reports'&&<div><button onClick={()=>window.print()}>Download PDF</button>{reports.map(r=><article key={r.id}><h3>{r.title}</h3><p>{r.executiveSummary}</p><p>Top critical risks: {r.topRisks.map(t=>t.title).join(', ')}</p></article>)}</div>}
  {page==='Settings'&&<div><p>{organization.name} | {organization.industry} | {organization.country}</p><p>Roles: Admin, Risk Manager, Auditor, Viewer</p><label>AI Language <select value={language} onChange={e=>setLanguage(e.target.value)}><option value='en'>English</option><option value='az'>Azerbaijani</option></select></label></div>}
  </main></div>
}
function Documents({docs,setDocs,runAI,ai}){const [name,setName]=useState('');const [text,setText]=useState('');return <div><input placeholder='Document name' value={name} onChange={e=>setName(e.target.value)}/><textarea placeholder='Paste confidential document text' value={text} onChange={e=>setText(e.target.value)}></textarea><button onClick={()=>{setDocs(d=>[{id:`doc-${d.length+1}`,organizationId:'org-1',name,type:'Procedure',uploadedAt:new Date().toISOString(),summary:text.slice(0,160),detectedRisks:['Operational Risk'],missingEvidence:['Approval metadata']},...d]);runAI('summary',{text})}}>Analyze Document</button><ul>{docs.map(d=><li key={d.id}>{d.name} - {d.summary}</li>)}</ul><pre>{ai}</pre></div>}
const card=(t,v)=><div className='card'><h3>{t}</h3><p>{v}</p></div>;
